name: learnprogres
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # UI & Typography
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  percent_indicator: ^4.2.3

  # Networking & Storage
  http: ^1.2.0
  shared_preferences: ^2.2.2

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
